MAX_ARG = 0
MAX_CALLBACK = 10
CALLBACK_TYPES = 8
DLTYPE[CHAR][:sym]  = true
DLTYPE[SHORT][:sym] = true
DLTYPE[INT][:sym]   = false
DLTYPE[LONG][:sym]  = true
DLTYPE[FLOAT][:sym] = true
DLTYPE[DOUBLE][:sym]= true
DLTYPE[VOIDP][:sym] = false
